version: "3.9"

services:
  redis:
    image: "redis:alpine3.16"
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      context: .
    image: pbarny/stratum-api
    ports:
      - "3033:3033"
    volumes:
    - ./:/app
    depends_on:
      - redis
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
