version: "3.9"

services:
  redis:
    image: "redis:alpine3.16"
    command: redis-server /usr/local/etc/redis/custom_redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./custom_redis.conf:/usr/local/etc/redis/custom_redis.conf
    networks:
      - backend

  app:
    build:
      context: .
    ports:
      - "3033:3033"
    volumes:
      - ./:/app
      - ${SSL_KEY_PATH}:/etc/letsencrypt/live/app-dev.stratumexchange.com/privkey.pem
      - ${SSL_CERT_PATH}:/etc/letsencrypt/live/app-dev.stratumexchange.com/fullchain.pem
    depends_on:
      - redis
    networks:
      - backend
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    user: "node:docker"

networks:
  backend:
